name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Build on Java ${{ matrix.java }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - run: java -version
      - run: mvn -v
      - run: mvn -B verify -Dgpg.skip=true
